name: Lint Code Base and Run Tests

on: [push, pull_request]

jobs:
  build:
    name: Lint and Test Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # 如果有其他依赖也可以在这里安装
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_black: true
          VALIDATE_PYTHON_PYLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Run pytest
        working-directory: src  # 假设测试文件在 src 目录下
        run: pytest
