name: Lint Code Base and Run Tests

on: [push, pull_request]

jobs:
  build:
    name: Lint and Test Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_black: true
          VALIDATE_PYTHON_PYLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pytest
        run: pip install pytest

      - name: Run pytest
        working-directory: SRH-berlin-software-engineering/src/test/unittest example.py
        run: pytest
